overrides:
  body-parser@<1.20.3: '>=1.20.3'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  cookie@<0.7.0: '>=0.7.0'
  ejs@<3.1.10: '>=3.1.10'
  ejs@<3.1.7: '>=3.1.7'
  express@<4.19.2: '>=4.19.2'
  express@<4.20.0: '>=4.20.0'
  jws@<3.2.3: '>=3.2.3'
  path-to-regexp@<0.1.10: '>=0.1.10'
  path-to-regexp@<0.1.12: '>=0.1.12'
  qs@>=6.7.0 <6.7.3: '>=6.7.3'
  send@<0.19.0: '>=0.19.0'
  serve-static@<1.16.0: '>=1.16.0'
